#!/bin/bash

# Entrypoint script for Docker container
set -euo pipefail

echo "=========================================="
echo "Fapplepie Downloader Docker Container"
echo "=========================================="
echo "Start time: $(date)"
echo "Download directory: ${DOWNLOAD_DIR}"
echo "Log directory: ${LOG_DIR}"
echo "=========================================="

# Create necessary directories
mkdir -p "${LOG_DIR}" "${DOWNLOAD_DIR}"

# Export runtime env for cron-triggered jobs.
write_cron_env_file() {
    local env_file="/app/.cron_env.sh"
    local var_names=(
        DOWNLOAD_DIR
        LOG_DIR
        NORDVPN_PROXY
        NORDVPN_USER
        NORDVPN_PASS
        NORDVPN_PROXY_SCOPE
        PROXY_SELF_CHECK_SAMPLE_URL
        SCRAPE_REQUEST_TIMEOUT_SECONDS
        SCRAPE_REQUEST_ATTEMPTS
        SCRAPE_REQUEST_BACKOFF_SECONDS
        SCRAPE_DELAY_SECONDS
        SCRAPE_DIRECT_FALLBACK_ON_403
        YT_DLP_PATH
        ARIA2C_PATH
        TZ
        CRON_TZ
    )

    {
        echo "#!/bin/bash"
        echo "# Generated by /app/entrypoint.sh"
        echo "export RUNNING_IN_DOCKER=1"
        for name in "${var_names[@]}"; do
            if [ -n "${!name:-}" ]; then
                printf 'export %s=%q\n' "${name}" "${!name}"
            fi
        done
    } > "${env_file}"

    chmod 0600 "${env_file}"
    echo "Cron environment file written: ${env_file}"
}

# Function to setup cron
setup_cron() {
    local schedule="${CRON_SCHEDULE:-0 2 * * *}"  # Default: 2 AM daily
    local cron_file="/etc/cron.d/fapplepie"
    local cron_tz="${CRON_TZ:-${TZ:-UTC}}"
    
    echo "Setting up cron job..."
    echo "Schedule: ${schedule}"
    echo "Timezone: ${cron_tz}"

    write_cron_env_file
    
    # Use /etc/cron.d for deterministic in-container cron setup.
    cat > "${cron_file}" <<EOF
SHELL=/bin/bash
PATH=/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BASH_ENV=/app/.cron_env.sh
CRON_TZ=${cron_tz}
${schedule} root /app/daily_download.sh >> /proc/1/fd/1 2>> /proc/1/fd/2
EOF

    chmod 0644 "${cron_file}"

    echo "Cron job added successfully:"
    cat "${cron_file}"
}

# Function to run once (non-cron mode)
run_once() {
    echo "Running in one-time execution mode..."
    cd /app
    /venv/bin/python3 scraper.py --all
    exit $?
}

# Function to run cron daemon
run_cron() {
    setup_cron
    
    echo "Starting cron daemon..."
    echo "Container will run indefinitely"
    echo "Use --once flag or RUN_ONCE=1 to execute script once"
    
    # Start cron in foreground
    exec cron -f
}

# Parse arguments
if [ "${1:-}" = "once" ] || [ "${1:-}" = "--once" ]; then
    run_once
elif [ "${RUN_ONCE:-}" = "1" ]; then
    run_once
elif [ "${1:-}" = "cron" ] || [ -z "${1:-}" ]; then
    run_cron
else
    # Execute custom command
    exec "$@"
fi
